### ISSUE TITLE
All numeric strings passed as params are converted to numbers

### ISSUE THREAD

**Issue by argvil19** [syscoin/syscoin-js#15]
Title.

Examples:

```
"12345" => 12345
"asd123" => "asd123"
"asd" => "asd"
```

This is creating conflicts while using some methods like walletpassphrase. It accepts a string as a pwd, and when its numeric it sends an integer instead.

**Comment by dwasyluk** [comment]
Closing as obsolete. Please reopen if this is still an issue.
